version: '3'
services:
  db:
    image: postgres:14.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    command: "postgres -c 'max_connections=500'"
  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
  frontend:
    build: .
    command: "./bin/webpacker-dev-server"
    volumes:
      - '.:/app'
    ports:
      - '3035:3005'
    depends_on:
      - backend
volumes:
  postgres_data: {}
